### PR TITLE
Add SchemaGenerator API

### PR DESCRIPTION
**Pull request by mgravell**

### CODE REVIEW

**Comment by gustav3d** [comment]
Request and response has replaced each other in all the generated rpc methods.

**Comment by mgravell** [comment]
Yep, you're right. Will fix.

**Comment by mgravell** [comment]
@gustav3d fixed in protobuf-net 3.0.23

**Comment by gustav3d** [comment]
Thanks  a lot for the quick fix !!

**Comment by gustav3d** [comment]
For Stream, It's on the request param instead of the return.

**Comment by gustav3d** [comment]
For server streaming that is.

**Comment by mgravell** [comment]
I had one job! The sad thing is, I genuinely wrote a test for this. I just screwed up the test in exactly the same ways as the code. Thanks, will rectify. Again.

(Quietly looks embarrassed)

**Comment by mgravell** [comment]
3.0.24 @gustav3d

**Comment by gustav3d** [comment]
Thanks for fixing so fast !
It seems to work well now :)

**Comment by JohnGalt1717** [comment]
Is there any documentation on how to use this to, say put up Swagger GRPC or create a simple file browser within your service that protoc can use to generate say a dart client from the results?

**Comment by JohnGalt1717** [comment]
I run this on this on the following service defintion and I get: Data of this type has inbuilt behaviour, and cannot be added to a model in this way: System.String
```
	[ServiceContract(Name = "SystemService")]
	public interface ISystemService : IService
	{
		ValueTask<string> Ping(string name);
		ValueTask<string> PingLoggedIn();
	}
```

**Comment by mgravell** [comment]
Indeed, that probably shouldn't work. If it currently does: that's sort of
a bug. In gRPC you're meant to send DTOs, not primitives.

We want to make protobuf-net.Grpc fake over that bit automatically for you,
but that is not currently implemented.

**Comment by JohnGalt1717** [comment]
@mgravell Ok, makes sense and I'm not sure it should be implemented. Might want to clearly document this for protobuf.net though.

**Pull request merged**
