### PR TITLE
explore "push enumerable" ideas from #14

### PR DESCRIPTION
**Pull request by mgravell**
This is a tracking branch to explore ideas around push async enumerables

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@mgravell I'm just experimenting with this implementation in my code. If it makes it into prod can you add support for completeWriterOnCancellation (on AsAsyncEnumerable method)? There's no way to achieve this at the moment as those methods expect a Channel<T>

**Comment by mgravell** [comment]
@JuliusSweetland only just noticed your comment; will look in the week - thx for the feedback

**Comment by mgravell** [comment]
I'm not sure I'm happy with this; killing for now

**Comment by JuliusSweetland** [comment]
@mgravell I liked the idea, but I didn't need this implementation in the end. Thanks though.

**Pull request closed without merging**
