### PR TITLE
Client factory musings

### PR DESCRIPTION
**Pull request by mgravell**

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
@mgravell Hi Marc - let me know if I can help by testing any of the new client factory stuff.

**Comment by JuliusSweetland** [comment]
@mgravell Hi Marc. With James N-K's changes do you have everything you need to implement this?

**Comment by mgravell** [comment]
@JuliusSweetland did they get merged? I need to revisit

**Comment by JuliusSweetland** [comment]
@mgravell If you were waiting for this then yes: https://github.com/grpc/grpc-dotnet/pull/851

**Comment by JuliusSweetland** [comment]
@mgravell The changes look good - thanks Marc.

**Comment by JuliusSweetland** [comment]
@mgravell Do you have plans to release this on your MyGet? I'd love to try this out. Currently I'm having to:

1.services.AddHttpClient();
2.var httpClientFactory = provider.GetService<IHttpClientFactory>();

3.then inject the httpClientFactory into my client class and then create and configure the GrpcClient like this:

var httpClient = httpClientFactory.CreateClient();
httpClient.Timeout = Timeout.InfiniteTimeSpan;
var channel = GrpcChannel.ForAddress(serverUrl.ToString(), new GrpcChannelOptions
{
    HttpClient = httpClient,
    DisposeHttpClient = true
});

The main thing I'm hoping with the new AddCodeFirstGrpcClient extension method is that I can set the HttpClient (somewhere - it may not be a concern of this new code) to have infinite timeout.

Thanks.

**Comment by mgravell** [comment]
'tis merged

**Comment by Euan-McVie** [comment]
Hi,
I've just hit an issue where I am wanting to add interceptors on top of the channelbase. It appears that this contains the extension method changes that allow creating the client from the resulting callinvokers.

1. Am I correct in assuming that the callinvoker extension method will support interceptor wrapped channels (I can't see why not, but just checking)
2. What is the release timeline for this change reaching the nuget packages as we are developing stuff now and would love to not have to write a workaround if it is going to be soon.

**Comment by mgravell** [comment]
@Euan-McVie 

1. yes, should work fine
2. yesterday

**Comment by Euan-McVie** [comment]
Great Thanks, Confirm it is working with the interceptors. I checked yesterday morning, but was today before I got around to posting. Guess I should have checked again first 😃

**Pull request merged**
