### PR TITLE
netcoreapp3.0 => netstandard2.1

### PR DESCRIPTION
**Pull request by pengweiqhca**

### CODE REVIEW

**Comment by mgravell** [comment]
Question: why? What does this give you that the existing ns2.0 TFM doesn't?

**Comment by pengweiqhca** [comment]
ns2.0 need reference `Microsoft.Bcl.AsyncInterfaces`

**Comment by mgravell** [comment]
Ah, so your objective here is to retain the reduced dependency graph that nca3.0 gives. I'll need to take a look, but in principle, sure that makes sense.

**Comment by mgravell** [comment]
Since Grpc.Net.Client targets ns2.1, this seems fine and reasonable; merging - thanks

**Pull request merged**
