### PR TITLE
add HttpContextAccessor to surppot server context injecting (#33)

### PR DESCRIPTION
**Pull request by ElderJames**

### CODE REVIEW

**Comment by NickCraver** [comment]
Having the new extensions is nice, but why does this need to always inject one? Remember that there is an async cost (that’s why it’s not added by default) - I’d argue very few things should inject the context accessor, only doing so if it’s critical to their functionality.

As an aside: the namespace change for the existing extension is a good one, that’s the recommendation so intellisense works better.

**Comment by ElderJames** [comment]
I thinks we can implement the EnableCallContextPropagation optional method like server-side cilent in Grpc.Net, the difference here is code first.
We need to propagat the data likes authentication, trace, configration etc. with httpcontext headers during cross-service invocation.

**Comment by NickCraver** [comment]
I'm not sure how the changes are related though, in this PR. The extension methods work on an HttpContextAccessor, which you can get if one is registered. The other change is to _always register one_, regardless of if it's used. I strongly recommend not doing this in any library that doesn't absolutely need it. Docs telling the user to register one if they want to use it would be the appropriate path there. This is the common pattern, and why it has a specific extension method built into the framework to make it easy to do.

**Comment by ElderJames** [comment]
Ok, I have reverted it.

**Comment by mgravell** [comment]
Why are you changing the na.espace of an existing type? That's a huge breaking change. Also, why are you declaring things in `Microsoft.AspNetCore.Http`? Are there reasons? This feels wrong...

**Comment by NickCraver** [comment]
Oh hmm didn't realize this was 1.x - FWIW the namespace change to `.DepdendencyInjection` is correct but yeah: breaking. Microsoft has official guidance here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0, specifically:

> We recommended that apps follow this convention. Place extension methods in the **Microsoft.Extensions.DependencyInjection** namespace to encapsulate groups of service registrations.

I'm not sure about patterns w.r.t. HttpContextAccessor - agree on not putting there unless specifically instructed to do so.

**Comment by mgravell** [comment]
If moving it is correct: fine - but what we need to do is:

- leave the old type/methods in place (have them call the new ones)
- remove the `this` so they aren't extension methods any longer
- add `[Obsolete]`

By doing so, it isn't a hard break.

**Comment by mgravell** [comment]
Note: the "new" declarations only needs one method - the overload was because the v1.0 lacked the return value and second parameter. We don't need the overload in the new code - just make it one method with an optional parameter

**Comment by mgravell** [comment]
Looking at the guidance and context here, my vote would be to move both the `AddCodeFirstGrpc` and call-context extension methods to:

`Microsoft.Extensions.DependencyInjection.CodeFirstGrpcExtensions`

Thoughts?

**Comment by ElderJames** [comment]
Sorry,I think we can just add a call-context extension class in this PR and leave other changes to another.
The reason to declare it in `Microsoft.AspNetCore.Http`  is simply to follow the namespace which it extends.

**Pull request merged**
