### PR TITLE
add first stab at generators; doesn't work well yet

### PR DESCRIPTION
**Pull request by mgravell**
Current status: package ref of protobuf-net.Reflection breaks the world

### CODE REVIEW

**Comment by gustav3d** [comment]
You dont want to use https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/  ?

**Comment by mgravell** [comment]
@gustav3d if you pinged me on this (I'm a little confused by an email notification): that's exactly what it is using

**Comment by gustav3d** [comment]
Yes, your correct !  i got confused by that there was .reflection as name.
What your doing is great work :)

Myself is looking to somehow be able to from a server write pre serialized
entities that i have cached in RAM, (that i auto update on changes, updates
are rare vs read requests) .

You got any idea how i can implement that in your APi?.

Thanks
  Gustav

**Comment by mgravell** [comment]
@gustav3d I can't decipher the scenario you are describing. Probably the best thing would be to illustrate it with an example of what you are trying to do, if an imaginary yet somehow perfect API existed.

**Pull request closed without merging**
